server:
  port: 9090
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
        - id: service3
          uri: lb://service3
          predicates:
              - Path=/service3/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
